module.exports.homePageLocators = {
singupBtn:".shop-menu > .nav > :nth-child(4) > a",
nameInput:"input[name='name']",
emailInput:"[data-qa='signup-email']",
passowordInput: "input[name='password']",
singupbtn2: "[data-qa='signup-button']",
firstNameInput: "input[name='first_name']",
lastNameInput: "input[name='last_name']",
daysBtn: "[data-qa='days']",
monthsBtn: "[data-qa='months']",
yearsBtn: "[data-qa='years']",
andressInput: "input[name='address1']",
stateInput:"input[name='state']",
cityInput: "input[name='city']",
zipCodeInput: "input[name='zipcode']",
mobileNumber: "input[name='mobile_number']",
createAccountBtn: "[data-qa='create-account']",
continueBtn: "[data-qa='continue-button']",
deleteAccountBtn: ".shop-menu > .nav > :nth-child(5) > a",
letterBtn: "#newsletter",
offerBtn: "form > :nth-child(8)",
loginEmailInput: "[data-qa='login-email']",
loginPasswordInput: "[data-qa='login-password']",
loginBtn: "[data-qa='login-button']",
shopMenu: ".shop-menu > .nav > :nth-child(5) > a",
continue2btn: "[data-qa='continue-button']",
loginEmailInput: "[data-qa='login-email']",
loginpassword2Input: "[data-qa='login-password']",
logoutBtn: ".shop-menu > .nav > :nth-child(4) > a",


//Compras

addCartInput: ".features_items > :nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn",
addcart2Input: ".modal-footer > .btn",
cartBtn: ".shop-menu > .nav > :nth-child(3) > a",
cart2Btn: ".shop-menu > .nav > :nth-child(2) > a",
productBtn: ":nth-child(3) > .product-image-wrapper > .choose > .nav > li > a",
buyBtn: ".col-sm-6 > .btn",
BuyBtn2: ":nth-child(7) > .btn",
nameCardInput: "[data-qa='name-on-card']",
cardNumberInput: "[data-qa='card-number']",
cvcInput: "[data-qa='cvc']",
monthInput: "[data-qa='expiry-month']",
yearsInput: "[data-qa='expiry-year']",
payBtn: "[data-qa='pay-button']",
continuePayBtn: "[data-qa='continue-button']",
viewCartBtn: ".modal-body > :nth-child(2) > a > u",
orderPlaced: "[data-qa='order-placed'] > b",

//EnvioEmail

nameEmailInput: "[data-qa='name']",
email2Input: "[data-qa='email']",
subjectInput: "[data-qa='subject']",
msgInput: "[data-qa='message']",
uploadFile: "[name='upload_file']",
submitBtn: "[data-qa='submit-button']",
homeBtn: ".nav > :nth-child(1) > a",
contactBtn: ".shop-menu > .nav > :nth-child(8) > a",
productInfo: ".product-information > h2",
productSpan: ":nth-child(5) > span",
}